version: '3.9'

services:

  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.15
    container_name: chromadb
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reactFrontend
    ports:
      - '3000:3000'

    volumes:
      - frontend:/app/frontend

    depends_on:
      - backend
    networks:
      - net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: djangoBackend
    ports:
      - '8080:8080'

    volumes:
      - backend:/app/backend

    depends_on:
      - chroma
    networks:
      - net
  nginx:
    image: nginx:latest
    container_name: nginxReverseProxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8001:8001"
    depends_on:
      - frontend
      - backend
    networks:
      - net

volumes:
  index_data:
  backups:
  backend:
  frontend:


networks:
  net:
    driver: bridge
